name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Package
        run: ./gradlew assemble
